"""Initial migration: create tables

Revision ID: 53cb0434c044
Revises: 
Create Date: 2025-11-09 18:38:03.005726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cb0434c044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_table('chat_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('is_jackpot', sa.Boolean(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_activities_created_at'), 'chat_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_activities_is_jackpot'), 'chat_activities', ['is_jackpot'], unique=False)
    op.create_index(op.f('ix_chat_activities_user_id'), 'chat_activities', ['user_id'], unique=False)
    op.create_table('score_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_score', sa.Integer(), nullable=False),
    sa.Column('chat_score_min', sa.Integer(), nullable=False),
    sa.Column('chat_score_max', sa.Integer(), nullable=False),
    sa.Column('jackpot_chance', sa.Float(), nullable=False),
    sa.Column('multiplier_min', sa.Integer(), nullable=False),
    sa.Column('multiplier_max', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_bonus', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('chat_count', sa.Integer(), nullable=False),
    sa.Column('jackpot_count', sa.Integer(), nullable=False),
    sa.Column('max_jackpot', sa.Integer(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.Column('total_attendance', sa.Integer(), nullable=False),
    sa.Column('last_checkin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_chat_count'), 'users', ['chat_count'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_total_score'), 'users', ['total_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_total_score'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_chat_count'), table_name='users')
    op.drop_table('users')
    op.drop_table('score_configs')
    op.drop_index(op.f('ix_chat_activities_user_id'), table_name='chat_activities')
    op.drop_index(op.f('ix_chat_activities_is_jackpot'), table_name='chat_activities')
    op.drop_index(op.f('ix_chat_activities_created_at'), table_name='chat_activities')
    op.drop_table('chat_activities')
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
